project_id = "qxeodogwbdndgfslbyej"

[functions.impersonate-user]
verify_jwt = true

[functions.ai-content]
verify_jwt = false

[functions.track]
verify_jwt = false

[functions.verify-admin-pin]
verify_jwt = false
